Call tf-reusable wf.

diff --git a/.github/workflows/terraform-base-reusable-workflow.yaml b/.github/workflows/terraform-base-reusable-workflow.yaml
--- a/.github/workflows/terraform-base-reusable-workflow.yaml
+++ b/.github/workflows/terraform-base-reusable-workflow.yaml
@@ -1,5 +1,5 @@
-# Reusable terraform workflow restricted to folder.
-# Needs inputs to specify restricted folder.
+# Reusable terraform workflow RESTRICTED to a single folder.
+# CAUTION: Needs inputs to specify restricted folder.
 name: terraform-base-reusable-workflow
 
 on:
@@ -45,78 +45,67 @@ jobs:
       # Output the folder, we restrict terraform actions to
       - name: Show terraform folders
         run: |
-          echo "  AwsAccountName:    ${{ inputs.AwsAccountName }}"
-          echo "  AwsEnvironmentName:${{ inputs.AwsEnvironmentName }}"
-          echo "  Working dir:"
-          echo "    terraform/aws-environments/${{ inputs.AwsAccountName }}/${{ inputs.AwsEnvironmentName }}"
+          echo "  Working dir as {{ inputs.terraform-folder }}:${{ inputs.terraform-folder }}:"
+          echo "  Working dir as PWD :$(pwd):"
+          git status
 
-      # Only run terraform IF tf files changed:
-      # https://github.com/tj-actions/changed-files
-      - name: Check if TF files changed
-        id: changed-files-specific
-        uses: tj-actions/changed-files@v1.1.2
-        with:
-          # list files that need to be changed, to run THESE actions
-          files: |
-            terraform/aws-environments/${{ inputs.AwsAccountName }}/${{ inputs.AwsEnvironmentName }}/*tf
+      # - name: Terraform fmt
+      #   id: fmt
+      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
+      #   run: terraform fmt -check
 
-      - name: Terraform fmt
-        id: fmt
-        if: steps.changed-files-specific.outputs.any_changed == 'true'
-        run: terraform fmt -check
+      # - name: Terraform init
+      #   id: init
+      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
+      #   run: terraform init
+      #   continue-on-error: false
 
-      - name: Terraform init
-        id: init
-        if: steps.changed-files-specific.outputs.any_changed == 'true'
-        run: terraform init
-        continue-on-error: false
+      # - name: Terraform validate
+      #   id: validate
+      #   if: steps.changed-files-specific.outputs.any_changed == 'true'
+      #   run: terraform validate
 
-      - name: Terraform validate
-        id: validate
-        if: steps.changed-files-specific.outputs.any_changed == 'true'
-        run: terraform validate
+      # - name: Terraform plan
+      #   id: plan
+      #   if: github.event_name == 'pull_request' && steps.changed-files-specific.outputs.any_changed == 'true'
+      #   run: terraform plan -no-color
+      #   continue-on-error: true
 
-      - name: Terraform plan
-        id: plan
-        if: github.event_name == 'pull_request' && steps.changed-files-specific.outputs.any_changed == 'true'
-        run: terraform plan -no-color
-        continue-on-error: true
+      # - name: Update Pull Request
+      #   if: github.event_name == 'pull_request' && steps.changed-files-specific.outputs.any_changed == 'true'
+      #   uses: actions/github-script@v4.0.2
 
-      - name: Update Pull Request
-        if: github.event_name == 'pull_request' && steps.changed-files-specific.outputs.any_changed == 'true'
-        uses: actions/github-script@v4.0.2
+      #   env:
+      #     PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+      #   with:
+      #     github-token: ${{ secrets.GITHUB_TOKEN }}
+      #     script: |
+      #       const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+      #       #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+      #       #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+      #       #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
 
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+      #       <details><summary>Show Plan</summary>
 
-            <details><summary>Show Plan</summary>
+      #       \`\`\`\n
+      #       ${process.env.PLAN}
+      #       \`\`\`
 
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
+      #       </details>
 
-            </details>
+      #       *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
 
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+      #       github.issues.createComment({
+      #         issue_number: context.issue.number,
+      #         owner: context.repo.owner,
+      #         repo: context.repo.repo,
+      #         body: output
+      #       })
 
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure' && steps.changed-files-specific.outputs.any_changed == 'true'
+      #   run: exit 1
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure' && steps.changed-files-specific.outputs.any_changed == 'true'
-        run: exit 1
-
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/master' && github.event_name == 'push' && steps.changed-files-specific.outputs.any_changed == 'true'
-        run: terraform apply -auto-approve
+      # - name: Terraform Apply
+      #   if: github.ref == 'refs/heads/master' && github.event_name == 'push' && steps.changed-files-specific.outputs.any_changed == 'true'
+      #   run: terraform apply -auto-approve
